name: 简体化备份脚本

on:
  push:
  schedule:
    - cron: 0/30 * * * *
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 安装环境
        uses: actions/setup-python@master
        with:
          python-version: 3.11
      - name: 安装依赖
        run: |
          pip3 install -r requirements.txt
      - name: 开始转换
        run: |
          python3 convert.py
      - name: 测试
        id: get_version
        run: |
          echo ::set-output name=tag1::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=tag2::${GITHUB_REF#refs/*/}
      - name: 测试1
        run: |
          echo ${{ steps.get_version.outputs.tag1 }}
          echo ${{ steps.get_version.outputs.tag2 }}
