name: 简体化

on:
  push:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  convert:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 安装环境
        uses: actions/setup-python@master
        with:
          python-version: 3.11
      - name: 安装依赖
        run: |
          pip3 install -r requirements.txt
      - name: 开始转换
        run: |
          python3 convert.py
